### ISSUE TITLE
HTML: Add the Footer Section - Owner = Paul

### ISSUE THREAD

**Issue by JohnWGardner** [JohnWGardner/Weather_Web_App#11]
Task: Create a new section for the footer at the bottom of your HTML page.
Action: Use Bootstrap's footer class and columns to structure the content.

**Comment by Gambit1583** [comment]
## Footer
- Completed HTML and CSS for footer. Added social media links with favicons 
- Copyright added.
- Divs for about section and contact section commented out for later development.
